CREATE DATABASE application;

CREATE TABLE job_details (
    JOB_DETAILS_ID bigint(20) NOT NULL AUTO_INCREMENT,
    JOB_ID varchar(100) DEFAULT NULL,
    JOB_TITLE varchar(100) DEFAULT NULL,
    JOB_STATUS varchar(20) DEFAULT NULL,
    START_PROCESSING_TIMESTAMP varchar(100) NULL,
    FUTURE_EXECUTION_TIME bigint(20) NOT NULL,
    START_TIME bigint(20)  NULL,
    END_TIME bigint(20)  NULL,
    TOTAL_TIME bigint(20)  NULL,
    STATUS varchar(20) NOT NULL,
    CREATE_DTTM DATETIME,
    UPDATE_DTTM DATETIME ,
    PRIMARY KEY (JOB_DETAILS_ID)
);

INSERT INTO job_details (JOB_DETAILS_ID, JOB_ID, JOB_TITLE, JOB_STATUS, START_PROCESSING_TIMESTAMP, FUTURE_EXECUTION_TIME, START_TIME, END_TIME, TOTAL_TIME, STATUS, CREATE_DTTM, UPDATE_DTTM)
VALUES(1, 'JobImplOne', 'VdxJobImpl', 'PENDING', NULL, 100, NULL, NULL, NULL, 'ACTIVE', NOW(), NULL);
INSERT INTO job_details (JOB_DETAILS_ID, JOB_ID, JOB_TITLE, JOB_STATUS, START_PROCESSING_TIMESTAMP, FUTURE_EXECUTION_TIME, START_TIME, END_TIME, TOTAL_TIME, STATUS, CREATE_DTTM, UPDATE_DTTM)
VALUES(, 'JobImplOne', 'VdxJobImpl', 'PENDING', NULL, 100, NULL, NULL, NULL, 'ACTIVE', NOW(), NULL);
