CREATE DATABASE application;

CREATE TABLE job_details (
    JOB_DETAILS_ID bigint(20) NOT NULL AUTO_INCREMENT,
    JOB_ID varchar(100) DEFAULT NULL,
    JOB_TITLE varchar(100) DEFAULT NULL,
    JOB_STATUS varchar(20) DEFAULT NULL,
    STATUS char NOT NULL,
    START_DTTM DATETIME,
    CREATE_DTTM DATETIME,
    END_DTTM DATETIME,
    UPDATE_DTTM DATETIME ,
    PRIMARY KEY (JOB_DETAILS_ID)
);

INSERT INTO job_details (JOB_DETAILS_ID, JOB_ID, JOB_TITLE, JOB_STATUS, STATUS, START_DTTM, CREATE_DTTM, END_DTTM, UPDATE_DTTM)
VALUES(1, 'JobImplOne', 'VdxJobImpl', 'PENDING', 'ACTIVE', NULL, NOW(), NULL, NULL);
